version: '3.8'

services:

  frontend:
    build: ./stonefish-ps/
    volumes:
      - ./stonefish-ps:/app-ps
    ports:
      - 8080:80

  backend:
    build: .
    command: uvicorn stonefish:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    expose:
      - 8000
    environment:
      - REDIS_USER=redis
      - REDIS_PASSWORD=redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      - frontend

  redis:
    image: redis
    restart: always
    expose:
      - 6379